export const state = {
  CFG: null,
  wallet: null,
  noxClient: null,
  notes: [],
  log: [],
  history: [],
  localHist: [],
  view: "landing",
  sheet: null,
  tab: "portfolio",
  lendTab: "lend",
  asset: 1,
  proving: false,
  heartbeat: 0,
  prices: { eurUsd: 1.08 },
  mktBusy: false,
  mktSheetData: null,
  mkt: {
    myPositions: [],
    loadedAt: 0,
    loading: false,
    err: null,
  },
  swapFrom: 1,
  swapTo: 2,
};
